#!/usr/bin/python2.7
import json
import os
import time
import urllib2
from httplib import responses

from hosted import config, Node
from jsonparser import JsonParser
from log import log

config.restart_on_update()


def main():
    while 1:
        node = Node(os.environ['NODE'])
        node.send('/updating:%s' % ".")
        parser = JsonParser()

        url = config['sold_out_feed_url']
        log("Updating sold out list from: " + url)
        try:
            response = urllib2.urlopen(urllib2.Request(url, None, {'User-Agent': 'SoldOutScreen'}))
            data = response.read()
            node.write_json("feed.json", json.loads(data.decode("utf-8")))

            sold_out_events = parser.parse("feed.json", config['today_only'])
            if sold_out_events is not None:
                node.write_file('soldoutevents.txt', "\n".join(sold_out_events))
                log("--------")
                for line in sold_out_events:
                    log(line)
                log("--------")
                node.send('/updating:%s' % " ")

        except urllib2.HTTPError as e:
            log("Server responded with: " + str(e.code) + " " + responses[e.code])

        except urllib2.URLError as e:
            log(e.reason)

        log("Updating again in " + str(config['update_interval']) + " seconds")
        time.sleep(int(config['update_interval']))


if __name__ == "__main__":
    main()
