#!/usr/bin/python2.7
import os
import sys
import time
from datetime import datetime

from hosted import CONFIG, NODE
import importer

CONFIG.restart_on_update()

def set_update_time(val):
    with open('last_updated.txt', 'w') as f:
        f.write(str(val))
        f.close()

def write_to_file(list):
    with file('soldoutevents.txt.new', 'wb') as f:
        for event in list:
            f.write(str(event) + '\n')
    os.rename("soldoutevents.txt.new", "soldoutevents.txt")
    print >>sys.stderr, str(len(list)) + " sold out events at " + str(datetime.now().strftime("%H:%M:%S %d %b %Y"))

def main():
    while 1:
        if os.path.isfile("soldoutevents.txt") == False:
            write_to_file([])
        set_update_time('updating now')
        events = importer.get_soldout(CONFIG['sold_out_feed_url'], int(CONFIG['today_only'] == True))
        if events is not None:
            write_to_file(events)
            set_update_time(datetime.now().strftime("%H:%M:%S %d %b %Y"))
        time.sleep(int(CONFIG['update_interval']))

if __name__ == "__main__":
    main()
